package com.inossem.wms.model.sinobec.gp;

public class CountOrderFromSap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.rid
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.count_order
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String countOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.dn_item_num
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String dnItemNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.wh_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String whCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.mat_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String matCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.unit_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String unitCode;

    private String corpCode;

    private String lotNumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.ext0
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String ext0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.ext1
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.ext2
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private String ext2;

    private String ext10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_order_from_sap.status
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.rid
     *
     * @return the value of count_order_from_sap.rid
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.rid
     *
     * @param rid the value for count_order_from_sap.rid
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.count_order
     *
     * @return the value of count_order_from_sap.count_order
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getCountOrder() {
        return countOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.count_order
     *
     * @param countOrder the value for count_order_from_sap.count_order
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setCountOrder(String countOrder) {
        this.countOrder = countOrder == null ? null : countOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.dn_item_num
     *
     * @return the value of count_order_from_sap.dn_item_num
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getDnItemNum() {
        return dnItemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.dn_item_num
     *
     * @param dnItemNum the value for count_order_from_sap.dn_item_num
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setDnItemNum(String dnItemNum) {
        this.dnItemNum = dnItemNum == null ? null : dnItemNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.wh_code
     *
     * @return the value of count_order_from_sap.wh_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getWhCode() {
        return whCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.wh_code
     *
     * @param whCode the value for count_order_from_sap.wh_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setWhCode(String whCode) {
        this.whCode = whCode == null ? null : whCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.mat_code
     *
     * @return the value of count_order_from_sap.mat_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getMatCode() {
        return matCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.mat_code
     *
     * @param matCode the value for count_order_from_sap.mat_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setMatCode(String matCode) {
        this.matCode = matCode == null ? null : matCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.unit_code
     *
     * @return the value of count_order_from_sap.unit_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.unit_code
     *
     * @param unitCode the value for count_order_from_sap.unit_code
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    public String getCorpCode() {
        return corpCode;
    }

    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode == null ? null : corpCode.trim();
    }

    public String getLotNumb() {
        return lotNumb;
    }

    public void setLotNumb(String lotNumb) {
        this.lotNumb = lotNumb == null ? null : lotNumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.ext0
     *
     * @return the value of count_order_from_sap.ext0
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getExt0() {
        return ext0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.ext0
     *
     * @param ext0 the value for count_order_from_sap.ext0
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setExt0(String ext0) {
        this.ext0 = ext0 == null ? null : ext0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.ext1
     *
     * @return the value of count_order_from_sap.ext1
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.ext1
     *
     * @param ext1 the value for count_order_from_sap.ext1
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.ext2
     *
     * @return the value of count_order_from_sap.ext2
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.ext2
     *
     * @param ext2 the value for count_order_from_sap.ext2
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }


    public String getExt10() {
        return ext10;
    }

    public void setExt10(String ext10) {
        this.ext10 = ext10 == null ? null : ext10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_order_from_sap.status
     *
     * @return the value of count_order_from_sap.status
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_order_from_sap.status
     *
     * @param status the value for count_order_from_sap.status
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}
