package com.inossem.wms.enums;

public enum EnumReturnCode {
	// 成功
	RETURN_CODE_SUCCESS(1),
	/** 请求处理中 */
	RETURN_CODE_REQUEST_ALREADY_IN_PROGRESS_EXCEPTION(10),
	// 失败
	RETURN_CODE_FAILURE(1001),
	// 异常
	RETURN_CODE_EXCEPTION(1002),
	// 未登录
    RETURN_CODE_UNAUTH(1003),
	// 没有访问权限
    RETURN_CODE_ACCESS_DENY(1004),
    // 接口调用失败
	RETURN_CODE_INTERFACE_CALL_FAILURE(1005),
	// XX不存在
	RETURN_CODE_PRIMARY_KEY_NOT_EXIST(1007),
	// "参数错误",
	RETURN_CODE_PARAMETER_ERROR(1009),
	// "结果为空",
	RETURN_CODE_RESULT_EMPTY(1019),
	// "结果溢出",
	RETURN_CODE_RESULT_OVERFLOW(1020),
	// "未找到国际化信息",
	RETURN_CODE_RESULT_TEXT(1021),
	//单据号生成失败
	RETURN_CODE_SEQUENCE_GENERATE_FAILURE(1030),
	//批次号生成失败
	RETURN_CODE_BATCH_GENERATE_FAILURE(1031),
	//单据备注获取失败
	RETURN_CODE_RECEIPT_REMARK(1040),
	// bean转换异常
	RETURN_CODE_BEAN_CAST_EXCEPTION(1041),
	//借贷标识异常
	RETURN_CODE_DEBIT_CREDIT_EXCEPTION(1042),
	// 抬头备注新增修改失败
	RETURN_CODE_RECEIPT_REMARK_INSERT_OR_UPDATE_EXCEPTION(1055),
	// 仓库已被使用，不允许修改仓位等信息
	RETURN_CODE_WH_USED(1061),
	// "原单位与目标单位不能相同",
	RETURN_CODE_UNIT_CODE_NOT_SAME(1074),
	// "数量不能为0",
	RETURN_CODE_QTY_NOT_ZERO(1075),
	//用户编码为空
	RETURN_CODE_USER_CODE_NOT_ENOUGH(1077),
	//用户名称为空
	RETURN_CODE_USER_NAME_NOT_ENOUGH(1078),
	//用户有效期始为空
	RETURN_CODE_VALIDITY_BEGIN_DATE_NOT_ENOUGH(1082),
	//用户有效期始为空
	RETURN_CODE_VALIDITY_END_DATE_NOT_ENOUGH(1083),
	//用户编码已经存在
	RETURN_CODE_USER_CODE_ALREADY_EXIST(1084),
	//该用户不存在
	RETURN_CODE_USER_DOES_NOT_EXIST(1085),
	//用户编码不可以修改
	RETURN_CODE_USER_CODE_CAN_NOT_BE_MODIFIED(1086),
	//用户类型不可以修改
	RETURN_CODE_USER_TYPE_CAN_NOT_BE_MODIFIED(1087),
	// 仓位号在该仓库和存储类型下不存在
	RETURN_CODE_BIN_CODE_NOT_EXIST(1091),
	//旧密码输入错误
	RETURN_CODE_OLD_PASSWORD_INPUT_ERROR(1097),
	//两次新密码不一致
	RETURN_CODE_TWO_INCONSISTENT_NEW_PASSWORDS(1098),
	//新密码和旧密码不可以一致
	RETURN_CODE_NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_IDENTICAL(1099),
	//角色编码不可以为空
	RETURN_CODE_ROLE_CODE_NOT_ENOUGH(1108),
	//角色描述不可以为空
	RETURN_CODE_ROLE_NAME_NOT_ENOUGH(1109),
	//该角色编码已存在
	RETURN_CODE_ROLE_CODE_ALREADY_EXIST(1110),
	//该角色描述已存在
	RETURN_CODE_ROLE_NAME_ALREADY_EXIST(1111),
	//角色不存在
	RETURN_CODE_ROLE_DOES_NOT_EXIST(1112),
	//角色描述已被使用
	RETURN_CODE_ROLE_DESCRIPTION_HAS_BEEN_USED(1113),
	//没有此公司
	RETURN_CODE_NO_SUCH_CORP(1114),
	//公司已经存在
	RETURN_CODE_CORP_ALERADY_EXISTS(1117),
	//经办人不可以为空
	RETURN_CODE_NULL_ACTOR(1120),
	// 物料编码不可以为空
	RETURN_CODE_MATERIAL_CODING_CAN_NOT_BE_EMPTY(1128),
	//语言类型不可以为空
	RETURN_CODE_LANGUAGE_TYPES_CAN_NOT_BE_EMPTY(1129),
	// 物料描述不可以为空
	RETURN_CODE_MATERIAL_NAME_CAN_NOT_BE_EMPTY(1130),
	// 物料类型编码不可以为空
	RETURN_CODE_MATERIAL_TYPES_CODE_CAN_NOT_BE_EMPTY(1131),
	// 计量单位编码不可以为空
	RETURN_CODE_UNITCODE_CAN_NOT_BE_EMPTY(1132),
	// 物料组编码不可以为空
	RETURN_CODE_MATERIAL_GROUP_CODE_CAN_NOT_BE_EMPTY(1133),
	// 物料编码已经被使用
	RETURN_CODE_MATERIAL_CODE_HAVE_BEEN_USED(1134),
	// 物料编码不可以修改
	RETURN_CODE_MAT_CODE_CAN_NOT_BE_MODIFIED(1135),
	// 单位编码不可以修改
	RETURN_CODE_UNIT_CODE_CAN_NOT_BE_MODIFIED(1137),
	// 仓库号已存在
	RETURN_CODE_WH_CODE_EXIST(1138),
	// 存储类型已存在
	RETURN_CODE_TYPE_CODE_EXIST(1139),
	// 仓位已存在
	RETURN_CODE_BIN_CODE_EXIST(1140),
	//登录信息不正确
	RETURN_CODE_INCORRECT_LOGIN_INFORMATION(1141),
	//单据类型不可以为空
	RETURN_CODE_RECEIPT_TYPE_CAN_NOT_BE_EMPTY(1142),
	//单据编码不可以为空
	RETURN_CODE_RECEIPT_CODE_CAN_NOT_BE_EMPTY(1143),
	//行项目中存在相同的物料{0}和批次{1}信息
	RETURN_CODE_SAME_ROW_INFO(1146),
	//启用仓位入库计划不能为空
	RETURN_CODE_TASK_INPUT_NOT_EMPTY(1147),
	//启用仓位出库计划不能为空
	RETURN_CODE_TASK_OUTPUT_NOT_EMPTY(1148),
	//语言编码不能相同
	RETURN_CODE_LANGUAGE_CODE_NOT_SAME(1149),
	//参数长度不正确
	RETURN_CODE_PARAMETER_LENGTH_ERROR(1151),
	// 经办组{0}中存在此岗位，不能删除
	RETURN_CODE_GROUP_CONTAIN_THIS_POST_CANNOT_BE_DELETE(1168),
	// 请选择角色信息
	RETURN_CODE_POST_CONTAIN_ROLE_CANNOT_BE_NULL(1169),
	// 角色代码{0}未被分配用户，不能保存
	RETURN_CODE_ROLE_CONTAIN_USER_CANNOT_BE_NULL(1170),
	// 请选择岗位信息
	RETURN_CODE_GROUP_CONTAIN_POST_CANNOT_BE_NULL(1171),
	// 岗位代码{0}未被分配用户，不能保存
	RETURN_CODE_POST_CONTAIN_USER_CANNOT_BE_NULL(1172),
	// 岗位代码{0}已存在
	RETURN_CODE_POST_CODE_DO_EXIST(1173),
	// 经办组代码{0}已存在
	RETURN_CODE_GROUP_CODE_DO_EXIST(1174),
	// 业务类型{0}公司默认经办组已存在
	RETURN_CODE_RECEIPT_TYPE_DEFAULT_CORP_GROUP_HAS_EXIST(1175),
	// 业务类型{0}个人默认经办组已存在
	RETURN_CODE_RECEIPT_TYPE_DEFAULT_OWN_GROUP_HAS_EXIST(1176),
	// 当前盘点单不是所有的行项目都是计数状态，不能全部重盘
	RETURN_CODE_NOT_ALL_ROW_DATE_COUNTED_STATUS(1177),
	//无新增配置数据
	RETURN_CODE_NO_CONF(1193),
	//无效的查询物料
	RETURN_CODE_INVALID_MAT_CODE(1194),
	// {0}仓位冻结
	RETURN_CODE_BIN_FREEZING(1196),
	// 盘点人不能为空
	RETURN_CODE_STOCK_TAKE_USER_NOT_EMPTY(1207),
	// 单据不是已计数状态，不能全部重盘
	RETURN_CODE_APPROVAL_NOT_ALL_STOCK_TAKE(1217),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是审批状态，不能差异重盘
	RETURN_CODE_APPROVAL_NOT_DIFFERENCE_STOCK_TAKE(1218),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是仓位差异处理状态，不能差异重盘
	RETURN_CODE_BIN_NOT_DIFFERENCE_STOCK_TAKE(1219),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是批次差异处理状态，不能差异重盘
	RETURN_CODE_BATCH_NOT_DIFFERENCE_STOCK_TAKE(1220),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是审批状态，不能仓位差异处理
	RETURN_CODE_APPROVAL_NOT_BIN_DIFFERENCE_STOCK_TAKE(1221),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目已经是仓位处理状态，不能再次仓位差异处理
	RETURN_CODE_BIN_NOT_BIN_DIFFERENCE_STOCK_TAKE(1222),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是批次处理状态，不能仓位差异处理
	RETURN_CODE_BATCH_NOT_BIN_DIFFERENCE_STOCK_TAKE(1223),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是审批状态，不能批次差异处理
	RETURN_CODE_APPROVAL_NOT_BATCH_DIFFERENCE_STOCK_TAKE(1224),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是计数状态，不能批次差异处理
	RETURN_CODE_COUNT_NOT_BATCH_DIFFERENCE_STOCK_TAKE(1225),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目是批次处理状态，不能再次批次差异处理
	RETURN_CODE_BATCH_NOT_BATCH_DIFFERENCE_STOCK_TAKE(1226),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目已经是计数状态，不能再次计数
	RETURN_CODE_COUNT_NOT_COUNT_DIFFERENCE_STOCK_TAKE(1227),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目已经重新计数，不能差异重盘
	RETURN_CODE_AGAIN_COUNT_NOT_DIFFERENCE_STOCK_TAKE(1228),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目已经重新计数，不能仓位差异处理
	RETURN_CODE_AGAIN_COUNT_NOT_BIN_DIFFERENCE_STOCK_TAKE(1229),
	// 存储类型{0}仓位{1}批次{2}库存数量{3}实际数量{4}的行项目已经重新计数，不能批次差异处理
	RETURN_CODE_AGAIN_COUNT_NOT_BATCH_DIFFERENCE_STOCK_TAKE(1230),
	// 角色编码不能超过10位
	RETURN_CODE_ROLE_CODE_LENGTH_TOO_LONG(1231),
	// 角色描述不能超过100位
	RETURN_CODE_ROLE_NAME_LENGTH_TOO_LONG(1232),
	// 单据流保存失败
	RETURN_CODE_REL_RECEIPT_RID_GENERATE_FAILURE(1249),
	// 单据{0}行{1}对应的前续单据行必须唯一
	RETURN_CODE_PRE_RECEIPT_RID_MUST_BE_UNIQUE(1250),
	// 该仓库下的存储类型已经启用存储单元，所以仓库必须启用存储单元
	RETURN_CODE_WH_CELL_MUST_ENABLED(1251),
	/**仓库号{0}存储类型{1}仓位{2}没有配置对应的仓位*/
	RETURN_CODE_NOT_CONFIGURATION_BIN_CODE(1410),
	// 语言不存在
	RETURN_CODE_LANGUAGE_NOT_EXIST(2000),
	// 板块不存在
	RETURN_CODE_BOARD_NOT_EXIST(2001),
	// 公司不存在
	RETURN_CODE_CORP_NOT_EXIST(2002),
	// 工厂不存在
	RETURN_CODE_FACTORY_NOT_EXIST(2003),
	// 仓库{0}不存在
	RETURN_CODE_WAREHOUSE_NOT_EXIST(2005),
	// 存储类型不存在
	RETURN_CODE_STORAGE_TYPE_NOT_EXIST(2006),
	// 存储区不存在
	RETURN_CODE_STORAGE_SECTION_NOT_EXIST(2007),
	// 仓位不存在
	RETURN_CODE_STORAGE_BIN_NOT_EXIST(2008),
	// 物料不存在
	RETURN_CODE_MATERIAL_NOT_EXIST(2009),
	// 单位{0}不存在
	RETURN_CODE_UNIT_NOT_EXIST(2011),
	// 物料{1}单位{2}与{3}的换算关系不存在
	RETURN_CODE_REL_UNIT_NOT_EXIST(2011),
	// 系统配置错误
	RETURN_CODE_SYSTEM_CONFIG_ERROR(2013),
	// 单位{0}已存在
	RETURN_CODE_UNIT_ALREADY_EXIST(2017),
	// 物料{1}单位{2}与{3}的换算关系已存在
	RETURN_CODE_REL_UNIT_ALREADY_EXIST(2018),
	// 存储区已存在
	RETURN_CODE_STORAGE_SECTION_EXIST(2020),
	// 算术异常：ArithmeticException
	RETURN_CODE_ARITHMETIC_EXCEPTION(2100),
	// 空指针异常：NullPointerException
	RETURN_CODE_NULL_POINTER_EXCEPTION(2101),
	// 类型强制转换异常：ClassCastException
	RETURN_CODE_CLASS_CAST_EXCEPTION(2102),
	// 数组负下标异常：NegativeArrayException
	RETURN_CODE_NEGATIVE_ARRAY_SIZE_EXCEPTION(2103),
	// 数组下标越界异常：ArrayIndexOutOfBoundsException
	RETURN_CODE_ARRAY_INDEX_OUT_OF_BOUNDS_EXCEPTION(2104),
	// 违背安全原则异常：SecturityException
	RETURN_CODE_SECURITY_EXCEPTION(2105),
	// 文件已结束异常：EOFException
	RETURN_CODE_EOF_EXCEPTION(2106),
	// 文件未找到异常：FileNotFoundException
	RETURN_CODE_FILE_NOT_FOUND_EXCEPTION(2107),
	// 字符串转换为数字异常：NumberFormatException
	RETURN_CODE_NUMBER_FORMAT_EXCEPTION(2108),
	// 操作数据库异常：SQLException
	RETURN_CODE_SQL_EXCEPTION(2109),
	// 输入输出异常：IOException
	RETURN_CODE_IO_EXCEPTION(2110),
	// 方法未找到异常：NoSuchMethodException
	RETURN_CODE_NO_SUCH_METHOD_EXCEPTION(2111),
	// 必填岗位不全
	RETURN_CODE_REQUIRED_POST_NOT_ENOUGH_EXCEPTION(2116),
	// 仓库物料已存在
	RETURN_CODE_WH_MAT_EXISTED(2119),
	// {0}板块{1}公司{2}年{3}月账期已存在
	RETURN_CODE_ACCOUNT_PERIOD_EXIST (2122),
	// {0}板块{1}公司{2}年{3}月账期管理时间段冲突
	ERROR_CODE_ACCOUNT_PERIOD_TIME_BEGIN_END_EXIST (2123),
	//{}公司的帐期管理时间范围有重合
	RETURN_CODE_ACCOUNT_PERIOD_TIME_CONFLICT(2127),
	//
    RETURN_CODE_MAIL_MESSAGE_EXIST_NULL(3149),
    //任务已存在
    RETURN_CODE_SCHEDULED_IS_EXISTED(3160),
    //超过license限制
    RETURN_CODE_LICENSE_LIMIT_EXCEEDED(3161),

	//打印机不存在
	RETURN_CODE_PRINTER_IS_NOT_EXISTED(3162),

	RETURN_CODE_GOODS_HAVE_BEEN_DELIVERED(3163),

    /********************sinobec***code值从8000开始**********************/

    // "配货数量异常",
  	RETURN_CODE_QUANTITY_DIFFERENCES(1051),
  	// "行项目为空",
  	RETURN_CODE_EMPTY_ITEM(1012),
  	// "参数不全",
  	RETURN_CODE_PARAMETER_LOST(1008),


    // 通用库存修改缺少参数STOCK_ID
    RETURN_CODE_SINOBEC_STOCK_PARAMTER_REQUIRE_STOCK_ID(8000),
    // 通用库存修改缺少参数WEIGHT_QTY
    RETURN_CODE_SINOBEC_STOCK_PARAMTER_REQUIRE_WEIGHT_QTY(8001),
    // 通用库存修改缺少参数RECEIPT_QTY
    RETURN_CODE_SINOBEC_STOCK_PARAMTER_REQUIRE_RECEIPT_QTY(8002),
    // 通用库存修改缺少参数BIN_WEIGHT_QTY
    RETURN_CODE_SINOBEC_STOCK_PARAMTER_REQUIRE_BIN_WEIGHT_QTY(8003),
    //{0}bundle库存不足
    RETURN_CODE_SINOBEC_STOCK_NOT_ENOUGH(8004),
    //ins凭证仓位信息不全
    RETURN_CODE_SINOBEC_INS_REQUIRE_BIN(8005),
    //仓位号{0}不存在
    RETURN_CODE_SINOBEC_BIN_CODE_NOT_EXIST(8006),
    //未查到bundle信息
    RETURN_CODE_SINOBEC_BUNDLE_CODE_NOT_EXIST(8007),

    //{0}bundle无法上架
    RETURN_CODE_SINOBEC_BUNDLE_CAN_NOT_LOAD(8008),
    //{0}bundle获取推荐仓位失败
    RETURN_CODE_SINOBEC_CAN_NOT_GET_RECOMMEND_BIN(8009),
    //{0}bundle未确认仓位
    RETURN_CODE_SINOBEC_BUNDLE_REQUIRED_CONFIRM_BIN(8010),
    //{0}bundle确认仓位与推荐仓位不一致
    RETURN_CODE_SINOBEC_BUNDLE_REQUIRED_CONFIRM_BIN_NOT_SAME_WITH_TARGET_BIN(8011),
    //{0}仓位超重
    RETURN_CODE_SINOBEC_BIN_OVER_WEIGHT(8012),
    //{0}bundle无法整理
    RETURN_CODE_SINOBEC_BUNDLE_CAN_NOT_ARRANGE(8013),

	//单据已冲销不可创建
	RETURN_CODE_SINOBEC_DOCUMENT_REVERSED_CANNOT_BE_CREATED(8014),
	//已完成整理单无法删除
    RETURN_CODE_SINOBEC_COMPLETE_TASK_CAN_NOT_DELETE(8015),
    //未找到单据{0}
    RETURN_CODE_SINOBEC_CAN_NOT_FIND_RECEIPT(8016),
    //单据{0}无操作行项目
    RETURN_CODE_SINOBEC_NOT_FIND_ITEM(8017),
    //仓位最大载重需要大于当前载重
    RETURN_CODE_SINOBEC_BIN_MAX_WEIGHT_NEED_GREATER_THAN_CURRENT_WEIGHT(8018),
    //上传最大版本apk
    RETURN_CODE_SINOBEC_PLEASE_UPLOAD_NEWEST_APK(8019),
    //上传失败
    RETURN_CODE_SINOBEC_UPLOAD_FAILED(8020),
    //单据已完成
    RETURN_CODE_SINOBEC_RECEIPT_IS_COMPLETE(8021),
    //单据未拣货
    RETURN_CODE_SINOBEC_RECEIPT_IS_NOT_PICK(8022),

    //获取GPtoken失败
    RETURN_CODE_SINOBEC_GET_GP_TOKEN_FAILED(8023),
    //excel 参数错误
    RETURN_CODE_SINOBEC_EXCEL_PARAMETER_ERROR(8024),
    //已发货
    RETURN_CODE_SINOBEC_SELECTED_DOCUMENT_HAS_ALREADY_DELIVERED(8025),
    //未配置邮件接收人
    RETURN_CODE_SINOBEC_MAIL_RECIPIENT_IS_NOT_CONFIGURED(8026),
    //{0}
    RETURN_CODE_SINOBEC_EXCEPTION(8027),

    RETURN_CODE_SINOBEC_BUNDLE_BIN_EMPTY_OR_FROZEN(8028),
    RETURN_CODE_SINOBEC_BIN_FROZEN(8029),


    /********************sinobec***************************************/

    RETURN_CODE_SAP_EXCEPTION(9001)

	;


	/** 枚举值 */
	private Integer value;

	private EnumReturnCode(Integer value) {
		this.value = value;
	}

	public Integer getValue() {
		return value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}
}
