package com.inossem.wms.model.sinobec.unload;

import com.inossem.wms.model.sinobec.dic.SinobecDicBundleInfo;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 下架下级vo
 */
public class UnLoadShelfUnpackVo extends SinobecDicBundleInfo implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3111060547870527826L;

	private Integer stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.bundle_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String bundleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.shipping_ref
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String shippingRef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.wh_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String whCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.type_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.bin_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String binCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.weight_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String weightUnitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.weight_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private BigDecimal weightQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.create_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.modify_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.receipt_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String receiptUnitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.receipt_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private BigDecimal receiptQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.create_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.modify_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Integer modifyUserId;


    private String receiptCode;

    private String receiptRid;

    private String receiptBid;

    private Integer receiptType;

    @ApiModelProperty(value = "是否拆包" )
    private boolean unpack;

    @ApiModelProperty(value = "拆包数量" )
    private BigDecimal unpackNum;

    public Integer getStockId() {
        return stockId;
    }

    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    @Override
    public String getBundleCode() {
        return bundleCode;
    }

    @Override
    public void setBundleCode(String bundleCode) {
        this.bundleCode = bundleCode;
    }

    @Override
    public String getShippingRef() {
        return shippingRef;
    }

    @Override
    public void setShippingRef(String shippingRef) {
        this.shippingRef = shippingRef;
    }

    public String getWhCode() {
        return whCode;
    }

    public void setWhCode(String whCode) {
        this.whCode = whCode;
    }

    public String getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public String getBinCode() {
        return binCode;
    }

    public void setBinCode(String binCode) {
        this.binCode = binCode;
    }

    public String getWeightUnitCode() {
        return weightUnitCode;
    }

    public void setWeightUnitCode(String weightUnitCode) {
        this.weightUnitCode = weightUnitCode;
    }

    public BigDecimal getWeightQty() {
        return weightQty;
    }

    public void setWeightQty(BigDecimal weightQty) {
        this.weightQty = weightQty;
    }

    @Override
    public Date getCreateTime() {
        return createTime;
    }

    @Override
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public Date getModifyTime() {
        return modifyTime;
    }

    @Override
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getReceiptUnitCode() {
        return receiptUnitCode;
    }

    public void setReceiptUnitCode(String receiptUnitCode) {
        this.receiptUnitCode = receiptUnitCode;
    }

    public BigDecimal getReceiptQty() {
        return receiptQty;
    }

    public void setReceiptQty(BigDecimal receiptQty) {
        this.receiptQty = receiptQty;
    }

    @Override
    public Integer getCreateUserId() {
        return createUserId;
    }

    @Override
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    @Override
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    @Override
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    @Override
    public String getReceiptCode() {
        return receiptCode;
    }

    @Override
    public void setReceiptCode(String receiptCode) {
        this.receiptCode = receiptCode;
    }

    @Override
    public String getReceiptRid() {
        return receiptRid;
    }

    @Override
    public void setReceiptRid(String receiptRid) {
        this.receiptRid = receiptRid;
    }

    public String getReceiptBid() {
        return receiptBid;
    }

    public void setReceiptBid(String receiptBid) {
        this.receiptBid = receiptBid;
    }

    @Override
    public Integer getReceiptType() {
        return receiptType;
    }

    @Override
    public void setReceiptType(Integer receiptType) {
        this.receiptType = receiptType;
    }

    public boolean isUnpack() {
        return unpack;
    }

    public void setUnpack(boolean unpack) {
        this.unpack = unpack;
    }

    public BigDecimal getUnpackNum() {
        return unpackNum;
    }

    public void setUnpackNum(BigDecimal unpackNum) {
        this.unpackNum = unpackNum;
    }
}
