package com.inossem.wms.dao.sinobec.dic;

import com.inossem.wms.model.sinobec.dic.SinobecDicBundleInfo;
import com.inossem.wms.model.sinobec.dic.SinobecDicBundleInfoKey;
import com.inossem.wms.model.sinobec.unload.UnLoadShelfUnpackVo;

import java.util.List;

public interface SinobecDicBundleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_dic_bundle_info
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    int deleteByPrimaryKey(SinobecDicBundleInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_dic_bundle_info
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    int insert(SinobecDicBundleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_dic_bundle_info
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    int insertSelective(SinobecDicBundleInfo record);

    int insertAll(SinobecDicBundleInfo bundleInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_dic_bundle_info
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    SinobecDicBundleInfo selectByPrimaryKey(SinobecDicBundleInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_dic_bundle_info
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    int updateByPrimaryKeySelective(SinobecDicBundleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_dic_bundle_info
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    int updateByPrimaryKey(SinobecDicBundleInfo record);

    /**
     * 批量插入bundle信息  已存在 则根据主键更新
     * @param bundleList
     * @return
     */
    int insertOrUpdateList(List<SinobecDicBundleInfo> bundleList);


    UnLoadShelfUnpackVo selectBySotckId(Integer stockid);

    List<SinobecDicBundleInfo> selectByMatAndBatch(SinobecDicBundleInfo record);
    List<SinobecDicBundleInfo> selectByMatAndVin(SinobecDicBundleInfo record);
    List<SinobecDicBundleInfo> selectByMatAndEng(SinobecDicBundleInfo record);

    String selectCorpCodeByBundleCode(String bundleCode);

    String selectMatCodeByBundleCode(String bundleCode);

    int findBundleCode(String bundleCode);

}
