package com.inossem.wms.dao.sinobec.rel;

import java.util.List;

import com.inossem.wms.model.sinobec.rel.SinobecRelMailReceipt;
import com.inossem.wms.model.sinobec.rel.SinobecRelMailReceiptKey;
import com.inossem.wms.vo.sinobec.SinobecRelMailReceiptVo;

public interface SinobecRelMailReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_rel_mail_receipt
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    int deleteByPrimaryKey(SinobecRelMailReceiptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_rel_mail_receipt
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    int insert(SinobecRelMailReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_rel_mail_receipt
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    int insertSelective(SinobecRelMailReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_rel_mail_receipt
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    SinobecRelMailReceipt selectByPrimaryKey(SinobecRelMailReceiptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_rel_mail_receipt
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    int updateByPrimaryKeySelective(SinobecRelMailReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_rel_mail_receipt
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    int updateByPrimaryKey(SinobecRelMailReceipt record);
    
    /**
     * 根据单据类型查询Email
     *
     * @param receiptType
     * @return
     */
    List<SinobecRelMailReceiptVo> getEmailListByReceipt(Integer receiptType);
    
}