package com.inossem.wms.model.sinobec.dic;

import java.util.Date;

public class SinobecDicBundleInfo extends SinobecDicBundleInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.receipt_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String receiptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.receipt_rid
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String receiptRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.receipt_type
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private Integer receiptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.heat_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String heatCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.skid_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String skidCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.mat_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String matCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.unit_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.corp_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String corpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.item_numb
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String itemNumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.lot_numb
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String lotNumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.input_date
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private Date inputDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.stock_status
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String stockStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.create_user_id
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.modify_user_id
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private Integer modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.create_time
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.modify_time
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private Date modifyTime;
    

    private String ext0;// VIN	
    
    private String ext1;//ENG
    
    private String ext2;//SKU TYPE
    
    private String ext3;
    
    private String ext4;
    
    private String ext5;
    
    private String ext6;
    
    private String ext7;
    
    private String ext8;
    
    private String ext9;
    
    private String ext10;
    
    private String ext11;
    
    private String ext12;
    
    private String ext13;
    
    private String ext14;
    
    private String ext15;

    public String getExt0() {
		return ext0;
	}

	public void setExt0(String ext0) {
		this.ext0 = ext0;
	}

	public String getExt1() {
		return ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	public String getExt2() {
		return ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

    public String getExt3() {
		return ext3;
	}

	public void setExt3(String ext3) {
		this.ext3 = ext3;
	}

	public String getExt4() {
		return ext4;
	}

	public void setExt4(String ext4) {
		this.ext4 = ext4;
	}

	public String getExt5() {
		return ext5;
	}

	public void setExt5(String ext5) {
		this.ext5 = ext5;
	}

	public String getExt6() {
		return ext6;
	}

	public void setExt6(String ext6) {
		this.ext6 = ext6;
	}

	public String getExt7() {
		return ext7;
	}

	public void setExt7(String ext7) {
		this.ext7 = ext7;
	}

	public String getExt8() {
		return ext8;
	}

	public void setExt8(String ext8) {
		this.ext8 = ext8;
	}

	public String getExt9() {
		return ext9;
	}

	public void setExt9(String ext9) {
		this.ext9 = ext9;
	}
	
	

	public String getExt10() {
		return ext10;
	}

	public void setExt10(String ext10) {
		this.ext10 = ext10;
	}

	public String getExt11() {
		return ext11;
	}

	public void setExt11(String ext11) {
		this.ext11 = ext11;
	}

	public String getExt12() {
		return ext12;
	}

	public void setExt12(String ext12) {
		this.ext12 = ext12;
	}

	public String getExt13() {
		return ext13;
	}

	public void setExt13(String ext13) {
		this.ext13 = ext13;
	}

	public String getExt14() {
		return ext14;
	}

	public void setExt14(String ext14) {
		this.ext14 = ext14;
	}

	public String getExt15() {
		return ext15;
	}

	public void setExt15(String ext15) {
		this.ext15 = ext15;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.receipt_code
     *
     * @return the value of sinobec_dic_bundle_info.receipt_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getReceiptCode() {
        return receiptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.receipt_code
     *
     * @param receiptCode the value for sinobec_dic_bundle_info.receipt_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setReceiptCode(String receiptCode) {
        this.receiptCode = receiptCode == null ? null : receiptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.receipt_rid
     *
     * @return the value of sinobec_dic_bundle_info.receipt_rid
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getReceiptRid() {
        return receiptRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.receipt_rid
     *
     * @param receiptRid the value for sinobec_dic_bundle_info.receipt_rid
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setReceiptRid(String receiptRid) {
        this.receiptRid = receiptRid == null ? null : receiptRid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.receipt_type
     *
     * @return the value of sinobec_dic_bundle_info.receipt_type
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public Integer getReceiptType() {
        return receiptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.receipt_type
     *
     * @param receiptType the value for sinobec_dic_bundle_info.receipt_type
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setReceiptType(Integer receiptType) {
        this.receiptType = receiptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.heat_code
     *
     * @return the value of sinobec_dic_bundle_info.heat_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getHeatCode() {
        return heatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.heat_code
     *
     * @param heatCode the value for sinobec_dic_bundle_info.heat_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setHeatCode(String heatCode) {
        this.heatCode = heatCode == null ? null : heatCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.skid_code
     *
     * @return the value of sinobec_dic_bundle_info.skid_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getSkidCode() {
        return skidCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.skid_code
     *
     * @param skidCode the value for sinobec_dic_bundle_info.skid_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setSkidCode(String skidCode) {
        this.skidCode = skidCode == null ? null : skidCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.mat_code
     *
     * @return the value of sinobec_dic_bundle_info.mat_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getMatCode() {
        return matCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.mat_code
     *
     * @param matCode the value for sinobec_dic_bundle_info.mat_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setMatCode(String matCode) {
        this.matCode = matCode == null ? null : matCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.unit_code
     *
     * @return the value of sinobec_dic_bundle_info.unit_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.unit_code
     *
     * @param unitCode the value for sinobec_dic_bundle_info.unit_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.corp_code
     *
     * @return the value of sinobec_dic_bundle_info.corp_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getCorpCode() {
        return corpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.corp_code
     *
     * @param corpCode the value for sinobec_dic_bundle_info.corp_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode == null ? null : corpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.item_numb
     *
     * @return the value of sinobec_dic_bundle_info.item_numb
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getItemNumb() {
        return itemNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.item_numb
     *
     * @param itemNumb the value for sinobec_dic_bundle_info.item_numb
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setItemNumb(String itemNumb) {
        this.itemNumb = itemNumb == null ? null : itemNumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.lot_numb
     *
     * @return the value of sinobec_dic_bundle_info.lot_numb
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getLotNumb() {
        return lotNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.lot_numb
     *
     * @param lotNumb the value for sinobec_dic_bundle_info.lot_numb
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setLotNumb(String lotNumb) {
        this.lotNumb = lotNumb == null ? null : lotNumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.input_date
     *
     * @return the value of sinobec_dic_bundle_info.input_date
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.input_date
     *
     * @param inputDate the value for sinobec_dic_bundle_info.input_date
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.stock_status
     *
     * @return the value of sinobec_dic_bundle_info.stock_status
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getStockStatus() {
        return stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.stock_status
     *
     * @param stockStatus the value for sinobec_dic_bundle_info.stock_status
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setStockStatus(String stockStatus) {
        this.stockStatus = stockStatus == null ? null : stockStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.create_user_id
     *
     * @return the value of sinobec_dic_bundle_info.create_user_id
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.create_user_id
     *
     * @param createUserId the value for sinobec_dic_bundle_info.create_user_id
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.modify_user_id
     *
     * @return the value of sinobec_dic_bundle_info.modify_user_id
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.modify_user_id
     *
     * @param modifyUserId the value for sinobec_dic_bundle_info.modify_user_id
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.create_time
     *
     * @return the value of sinobec_dic_bundle_info.create_time
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.create_time
     *
     * @param createTime the value for sinobec_dic_bundle_info.create_time
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.modify_time
     *
     * @return the value of sinobec_dic_bundle_info.modify_time
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.modify_time
     *
     * @param modifyTime the value for sinobec_dic_bundle_info.modify_time
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
    
    private String vendorCode;

	private String vendorName;

	public String getVendorCode() {
		return vendorCode;
	}

	public void setVendorCode(String vendorCode) {
		this.vendorCode = vendorCode;
	}

	public String getVendorName() {
		return vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}
}