package com.inossem.wms.model.sinobec.dic;

public class SinobecDicBundleInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.bundle_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String bundleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_dic_bundle_info.shipping_ref
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    private String shippingRef;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.bundle_code
     *
     * @return the value of sinobec_dic_bundle_info.bundle_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getBundleCode() {
        return bundleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.bundle_code
     *
     * @param bundleCode the value for sinobec_dic_bundle_info.bundle_code
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setBundleCode(String bundleCode) {
        this.bundleCode = bundleCode == null ? null : bundleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_dic_bundle_info.shipping_ref
     *
     * @return the value of sinobec_dic_bundle_info.shipping_ref
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public String getShippingRef() {
        return shippingRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_dic_bundle_info.shipping_ref
     *
     * @param shippingRef the value for sinobec_dic_bundle_info.shipping_ref
     *
     * @mbg.generated Mon Mar 23 11:10:44 CST 2020
     */
    public void setShippingRef(String shippingRef) {
        this.shippingRef = shippingRef == null ? null : shippingRef.trim();
    }
}