package com.inossem.wms.model.sinobec.rel;

public class SinobecRelMailReceiptKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_rel_mail_receipt.receipt_type
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    private Integer receiptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_rel_mail_receipt.user_id
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_rel_mail_receipt.receipt_type
     *
     * @return the value of sinobec_rel_mail_receipt.receipt_type
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    public Integer getReceiptType() {
        return receiptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_rel_mail_receipt.receipt_type
     *
     * @param receiptType the value for sinobec_rel_mail_receipt.receipt_type
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    public void setReceiptType(Integer receiptType) {
        this.receiptType = receiptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_rel_mail_receipt.user_id
     *
     * @return the value of sinobec_rel_mail_receipt.user_id
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_rel_mail_receipt.user_id
     *
     * @param userId the value for sinobec_rel_mail_receipt.user_id
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}