package com.inossem.wms.model.sinobec.rel;

public class SinobecRelMailReceipt extends SinobecRelMailReceiptKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_rel_mail_receipt.index
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_rel_mail_receipt.index
     *
     * @return the value of sinobec_rel_mail_receipt.index
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_rel_mail_receipt.index
     *
     * @param index the value for sinobec_rel_mail_receipt.index
     *
     * @mbg.generated Sat May 09 11:56:30 CST 2020
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}