package com.inossem.wms.dao.sinobec.gp;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.inossem.wms.model.sinobec.gp.CountOrderFromSap;

public interface CountOrderFromSapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_order_from_sap
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_order_from_sap
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    int insert(CountOrderFromSap record);
    
    int insertList(List<CountOrderFromSap> list);
    
    
    List<String> selectRejectableByCoAndStatus(List<String> cOrders);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_order_from_sap
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    int insertSelective(CountOrderFromSap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_order_from_sap
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    CountOrderFromSap selectByPrimaryKey(String rid);
    
    int selectByInfoKey(@Param("order")String order,@Param("sku")String sku,@Param("vin")String vin,@Param("eng")String eng);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_order_from_sap
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    int updateByPrimaryKeySelective(CountOrderFromSap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_order_from_sap
     *
     * @mbggenerated Fri Jun 11 21:08:14 EDT 2021
     */
    int updateByPrimaryKey(CountOrderFromSap record);
}