package com.inossem.wms.dao.sinobec.gp;

import java.util.List;

import com.inossem.wms.model.sinobec.gp.SinobecBizStockGp;
import com.inossem.wms.model.sinobec.query.StockBinVo;
import com.inossem.wms.model.sinobec.stock.SinobecStockVo;
import com.inossem.wms.model.sinobec.task.BundleQueryCo;

public interface SinobecBizStockGpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_biz_stock_gp
     *
     * @mbg.generated Wed May 06 16:30:55 CST 2020
     */
    int insert(SinobecBizStockGp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sinobec_biz_stock_gp
     *
     * @mbg.generated Wed May 06 16:30:55 CST 2020
     */
    int insertSelective(SinobecBizStockGp record);
    
    int deleteAll();
    
    int insertList(List<SinobecBizStockGp> list);

    List<SinobecStockVo> selectStockCorpToChangeListOnPaging(BundleQueryCo co);

    int changeCorp();
    
}