package com.inossem.wms.model.sinobec;

public class SinobecInsDocBinKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.ins_doc_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String insDocCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.ins_doc_rid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String insDocRid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.ins_doc_code
     *
     * @return the value of sinobec_ins_doc_bin.ins_doc_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getInsDocCode() {
        return insDocCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.ins_doc_code
     *
     * @param insDocCode the value for sinobec_ins_doc_bin.ins_doc_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setInsDocCode(String insDocCode) {
        this.insDocCode = insDocCode == null ? null : insDocCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.ins_doc_rid
     *
     * @return the value of sinobec_ins_doc_bin.ins_doc_rid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getInsDocRid() {
        return insDocRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.ins_doc_rid
     *
     * @param insDocRid the value for sinobec_ins_doc_bin.ins_doc_rid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setInsDocRid(String insDocRid) {
        this.insDocRid = insDocRid == null ? null : insDocRid.trim();
    }
}