package com.inossem.wms.model.sinobec;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

public class SinobecStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.stock_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Integer stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.bundle_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String bundleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.shipping_ref
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String shippingRef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.wh_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String whCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.type_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.bin_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String binCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.weight_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String weightUnitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.weight_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private BigDecimal weightQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.create_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.modify_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.receipt_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private String receiptUnitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.receipt_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private BigDecimal receiptQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.create_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_stock.modify_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    private Integer modifyUserId;


    private String receiptCode;

    private String receiptRid;

    private String receiptBid;

    private Integer taskId;

    private Integer outputId;

    private Integer receiptType;
    
    private String sourcetypeCode;
    
    private String sourceBinCode;
    
    private String lotNumb;
    
    private String ext9;

    /*******2021-10-18 新加*****/

    private String ext0;

    private String ext1;

    private String ext2;

    private String ext3;

    private String ext4;

    private String ext5;

    private String ext6;

    private String ext7;

    private String ext8;

    private String ext10;

    private String ext11;

    private String ext12;

    private String ext13;

    private String ext14;

    private String ext15;

    /*******2021-10-18 新加*****/

    @ApiModelProperty(value = "是否拆包" )
    private boolean unpack;

    @ApiModelProperty(value = "拆包数量" )
    private BigDecimal unpackNum;

    public Integer getOutputId() {
        return outputId;
    }

    public void setOutputId(Integer outputId) {
        this.outputId = outputId;
    }

    public Integer getTaskId() {
        return taskId;
    }

    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    public BigDecimal getUnpackNum() {
        return unpackNum;
    }

    public void setUnpackNum(BigDecimal unpackNum) {
        this.unpackNum = unpackNum;
    }

    public boolean isUnpack() {
        return unpack;
    }

    public void setUnpack(boolean unpack) {
        this.unpack = unpack;
    }

    public Integer getReceiptType() {
        return receiptType;
    }

    public void setReceiptType(Integer receiptType) {
        this.receiptType = receiptType;
    }

    public String getReceiptCode() {
        return receiptCode;
    }

    public void setReceiptCode(String receiptCode) {
        this.receiptCode = receiptCode;
    }

    public String getReceiptRid() {
        return receiptRid;
    }

    public void setReceiptRid(String receiptRid) {
        this.receiptRid = receiptRid;
    }

    public String getReceiptBid() {
        return receiptBid;
    }

    public void setReceiptBid(String receiptBid) {
        this.receiptBid = receiptBid;
    }
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.stock_id
     *
     * @return the value of sinobec_stock.stock_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.stock_id
     *
     * @param stockId the value for sinobec_stock.stock_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.bundle_code
     *
     * @return the value of sinobec_stock.bundle_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public String getBundleCode() {
        return bundleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.bundle_code
     *
     * @param bundleCode the value for sinobec_stock.bundle_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setBundleCode(String bundleCode) {
        this.bundleCode = bundleCode == null ? null : bundleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.shipping_ref
     *
     * @return the value of sinobec_stock.shipping_ref
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public String getShippingRef() {
        return shippingRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.shipping_ref
     *
     * @param shippingRef the value for sinobec_stock.shipping_ref
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setShippingRef(String shippingRef) {
        this.shippingRef = shippingRef == null ? null : shippingRef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.wh_code
     *
     * @return the value of sinobec_stock.wh_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public String getWhCode() {
        return whCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.wh_code
     *
     * @param whCode the value for sinobec_stock.wh_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setWhCode(String whCode) {
        this.whCode = whCode == null ? null : whCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.type_code
     *
     * @return the value of sinobec_stock.type_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.type_code
     *
     * @param typeCode the value for sinobec_stock.type_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.bin_code
     *
     * @return the value of sinobec_stock.bin_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public String getBinCode() {
        return binCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.bin_code
     *
     * @param binCode the value for sinobec_stock.bin_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setBinCode(String binCode) {
        this.binCode = binCode == null ? null : binCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.weight_unit_code
     *
     * @return the value of sinobec_stock.weight_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public String getWeightUnitCode() {
        return weightUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.weight_unit_code
     *
     * @param weightUnitCode the value for sinobec_stock.weight_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setWeightUnitCode(String weightUnitCode) {
        this.weightUnitCode = weightUnitCode == null ? null : weightUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.weight_qty
     *
     * @return the value of sinobec_stock.weight_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public BigDecimal getWeightQty() {
        return weightQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.weight_qty
     *
     * @param weightQty the value for sinobec_stock.weight_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setWeightQty(BigDecimal weightQty) {
        this.weightQty = weightQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.create_time
     *
     * @return the value of sinobec_stock.create_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.create_time
     *
     * @param createTime the value for sinobec_stock.create_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.modify_time
     *
     * @return the value of sinobec_stock.modify_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.modify_time
     *
     * @param modifyTime the value for sinobec_stock.modify_time
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.receipt_unit_code
     *
     * @return the value of sinobec_stock.receipt_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public String getReceiptUnitCode() {
        return receiptUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.receipt_unit_code
     *
     * @param receiptUnitCode the value for sinobec_stock.receipt_unit_code
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setReceiptUnitCode(String receiptUnitCode) {
        this.receiptUnitCode = receiptUnitCode == null ? null : receiptUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.receipt_qty
     *
     * @return the value of sinobec_stock.receipt_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public BigDecimal getReceiptQty() {
        return receiptQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.receipt_qty
     *
     * @param receiptQty the value for sinobec_stock.receipt_qty
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setReceiptQty(BigDecimal receiptQty) {
        this.receiptQty = receiptQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.create_user_id
     *
     * @return the value of sinobec_stock.create_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.create_user_id
     *
     * @param createUserId the value for sinobec_stock.create_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_stock.modify_user_id
     *
     * @return the value of sinobec_stock.modify_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_stock.modify_user_id
     *
     * @param modifyUserId the value for sinobec_stock.modify_user_id
     *
     * @mbg.generated Mon Mar 23 20:45:33 CST 2020
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    private String matCode;
    
    private String matExt1;
    
    

    public String getMatExt1() {
		return matExt1;
	}

	public void setMatExt1(String matExt1) {
		this.matExt1 = matExt1;
	}

	public String getMatCode() {
        return matCode;
    }

    public void setMatCode(String matCode) {
        this.matCode = matCode;
    }

	public String getSourcetypeCode() {
		return sourcetypeCode;
	}

	public void setSourcetypeCode(String sourcetypeCode) {
		this.sourcetypeCode = sourcetypeCode;
	}

	public String getSourceBinCode() {
		return sourceBinCode;
	}

	public void setSourceBinCode(String sourceBinCode) {
		this.sourceBinCode = sourceBinCode;
	}

	public String getLotNumb() {
		return lotNumb;
	}

	public void setLotNumb(String lotNumb) {
		this.lotNumb = lotNumb;
	}

	public String getExt9() {
		return ext9;
	}

	public void setExt9(String ext9) {
		this.ext9 = ext9;
	}

    public String getExt0() {
        return ext0;
    }

    public void setExt0(String ext0) {
        this.ext0 = ext0;
    }

    public String getExt1() {
        return ext1;
    }

    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    public String getExt2() {
        return ext2;
    }

    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }

    public String getExt3() {
        return ext3;
    }

    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }

    public String getExt4() {
        return ext4;
    }

    public void setExt4(String ext4) {
        this.ext4 = ext4;
    }

    public String getExt5() {
        return ext5;
    }

    public void setExt5(String ext5) {
        this.ext5 = ext5;
    }

    public String getExt6() {
        return ext6;
    }

    public void setExt6(String ext6) { this.ext6 = ext6; }

    public String getExt7() {
        return ext7;
    }

    public void setExt7(String ext7) { this.ext7 = ext7; }

    public String getExt8() {
        return ext8;
    }

    public void setExt8(String ext8) {
        this.ext8 = ext8;
    }

    public String getExt10() {
        return ext10;
    }

    public void setExt10(String ext10) {
        this.ext10 = ext10;
    }

    public String getExt11() {
        return ext11;
    }

    public void setExt11(String ext11) {
        this.ext11 = ext11;
    }

    public String getExt12() {
        return ext12;
    }

    public void setExt12(String ext12) {
        this.ext12 = ext12;
    }

    public String getExt13() {
        return ext13;
    }

    public void setExt13(String ext13) {
        this.ext13 = ext13;
    }

    public String getExt14() {
        return ext14;
    }

    public void setExt14(String ext14) {
        this.ext14 = ext14;
    }

    public String getExt15() {
        return ext15;
    }

    public void setExt15(String ext15) {
        this.ext15 = ext15;
    }

}