package com.inossem.wms.model.sinobec;

import java.math.BigDecimal;
import java.util.Date;

public class SinobecInsDocBin extends SinobecInsDocBinKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.mat_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String matCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.bundle_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String bundleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.shipping_ref
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String shippingRef;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.heat_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String heatCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.skid_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String skidCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.corp_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String corpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.item_numb
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String itemNumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.lot_numb
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String lotNumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.wh_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String whCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.type_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.bin_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String binCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.receipt_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String receiptUnitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.receipt_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private BigDecimal receiptQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.weight_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String weightUnitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.weight_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private BigDecimal weightQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.bin_weight_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String binWeightUnitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.bin_weight_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private BigDecimal binWeightQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.stock_status
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String stockStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.debit_credit
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String debitCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.refer_receipt_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String referReceiptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.refer_receipt_rid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String referReceiptRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.refer_receipt_bid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private String referReceiptBid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.refer_receipt_type
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private Integer referReceiptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.is_delete
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.write_off
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private Byte writeOff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.create_time
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.modify_time
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.create_user_id
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sinobec_ins_doc_bin.modify_user_id
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    private Integer modifyUserId;
    
    private Integer stockId;

    private String  corpName;

    private String matName;

    private String referReceiptTypeName;
    
    private String debitCreditName;

	private String ext0;
    
    private String ext1;
    
	private String ext2;
	
	private String ext3;
	
	private String ext4;
	
	private String ext5;
	
	private String ext6;
	
	private String ext7;
	
	private String ext8;
	
	private String ext9;
	
	private String ext10;
    private String ext11;
    private String ext12;
    private String ext13;
    private String ext14;
    private String ext15;
    
	public String getDebitCreditName() {
		return debitCreditName;
	}

	public void setDebitCreditName(String debitCreditName) {
		this.debitCreditName = debitCreditName;
	}
	
    public String getExt0() {
		return ext0;
	}

	public void setExt0(String ext0) {
		this.ext0 = ext0;
	}

	public String getExt1() {
		return ext1;
	}

	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}

	public String getExt2() {
		return ext2;
	}

	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}

	
	
    public String getExt3() {
		return ext3;
	}

	public void setExt3(String ext3) {
		this.ext3 = ext3;
	}

	public String getExt4() {
		return ext4;
	}

	public void setExt4(String ext4) {
		this.ext4 = ext4;
	}

	public String getExt5() {
		return ext5;
	}

	public void setExt5(String ext5) {
		this.ext5 = ext5;
	}

	public String getExt6() {
		return ext6;
	}

	public void setExt6(String ext6) {
		this.ext6 = ext6;
	}

	public String getExt7() {
		return ext7;
	}

	public void setExt7(String ext7) {
		this.ext7 = ext7;
	}

	public String getExt8() {
		return ext8;
	}

	public void setExt8(String ext8) {
		this.ext8 = ext8;
	}

	public String getExt9() {
		return ext9;
	}

	public void setExt9(String ext9) {
		this.ext9 = ext9;
	}
	
	

	public String getExt10() {
		return ext10;
	}

	public void setExt10(String ext10) {
		this.ext10 = ext10;
	}

	public String getExt11() {
		return ext11;
	}

	public void setExt11(String ext11) {
		this.ext11 = ext11;
	}

	public String getExt12() {
		return ext12;
	}

	public void setExt12(String ext12) {
		this.ext12 = ext12;
	}

	public String getExt13() {
		return ext13;
	}

	public void setExt13(String ext13) {
		this.ext13 = ext13;
	}

	public String getExt14() {
		return ext14;
	}

	public void setExt14(String ext14) {
		this.ext14 = ext14;
	}

	public String getExt15() {
		return ext15;
	}

	public void setExt15(String ext15) {
		this.ext15 = ext15;
	}

	public String getCorpName() {
        return corpName;
    }

    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.mat_code
     *
     * @return the value of sinobec_ins_doc_bin.mat_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getMatCode() {
        return matCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.mat_code
     *
     * @param matCode the value for sinobec_ins_doc_bin.mat_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setMatCode(String matCode) {
        this.matCode = matCode == null ? null : matCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.bundle_code
     *
     * @return the value of sinobec_ins_doc_bin.bundle_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getBundleCode() {
        return bundleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.bundle_code
     *
     * @param bundleCode the value for sinobec_ins_doc_bin.bundle_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setBundleCode(String bundleCode) {
        this.bundleCode = bundleCode == null ? null : bundleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.shipping_ref
     *
     * @return the value of sinobec_ins_doc_bin.shipping_ref
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getShippingRef() {
        return shippingRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.shipping_ref
     *
     * @param shippingRef the value for sinobec_ins_doc_bin.shipping_ref
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setShippingRef(String shippingRef) {
        this.shippingRef = shippingRef == null ? null : shippingRef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.heat_code
     *
     * @return the value of sinobec_ins_doc_bin.heat_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getHeatCode() {
        return heatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.heat_code
     *
     * @param heatCode the value for sinobec_ins_doc_bin.heat_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setHeatCode(String heatCode) {
        this.heatCode = heatCode == null ? null : heatCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.skid_code
     *
     * @return the value of sinobec_ins_doc_bin.skid_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getSkidCode() {
        return skidCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.skid_code
     *
     * @param skidCode the value for sinobec_ins_doc_bin.skid_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setSkidCode(String skidCode) {
        this.skidCode = skidCode == null ? null : skidCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.corp_code
     *
     * @return the value of sinobec_ins_doc_bin.corp_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getCorpCode() {
        return corpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.corp_code
     *
     * @param corpCode the value for sinobec_ins_doc_bin.corp_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode == null ? null : corpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.item_numb
     *
     * @return the value of sinobec_ins_doc_bin.item_numb
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getItemNumb() {
        return itemNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.item_numb
     *
     * @param itemNumb the value for sinobec_ins_doc_bin.item_numb
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setItemNumb(String itemNumb) {
        this.itemNumb = itemNumb == null ? null : itemNumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.lot_numb
     *
     * @return the value of sinobec_ins_doc_bin.lot_numb
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getLotNumb() {
        return lotNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.lot_numb
     *
     * @param lotNumb the value for sinobec_ins_doc_bin.lot_numb
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setLotNumb(String lotNumb) {
        this.lotNumb = lotNumb == null ? null : lotNumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.wh_code
     *
     * @return the value of sinobec_ins_doc_bin.wh_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getWhCode() {
        return whCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.wh_code
     *
     * @param whCode the value for sinobec_ins_doc_bin.wh_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setWhCode(String whCode) {
        this.whCode = whCode == null ? null : whCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.type_code
     *
     * @return the value of sinobec_ins_doc_bin.type_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.type_code
     *
     * @param typeCode the value for sinobec_ins_doc_bin.type_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.bin_code
     *
     * @return the value of sinobec_ins_doc_bin.bin_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getBinCode() {
        return binCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.bin_code
     *
     * @param binCode the value for sinobec_ins_doc_bin.bin_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setBinCode(String binCode) {
        this.binCode = binCode == null ? null : binCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.receipt_unit_code
     *
     * @return the value of sinobec_ins_doc_bin.receipt_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getReceiptUnitCode() {
        return receiptUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.receipt_unit_code
     *
     * @param receiptUnitCode the value for sinobec_ins_doc_bin.receipt_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setReceiptUnitCode(String receiptUnitCode) {
        this.receiptUnitCode = receiptUnitCode == null ? null : receiptUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.receipt_qty
     *
     * @return the value of sinobec_ins_doc_bin.receipt_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public BigDecimal getReceiptQty() {
        return receiptQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.receipt_qty
     *
     * @param receiptQty the value for sinobec_ins_doc_bin.receipt_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setReceiptQty(BigDecimal receiptQty) {
        this.receiptQty = receiptQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.weight_unit_code
     *
     * @return the value of sinobec_ins_doc_bin.weight_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getWeightUnitCode() {
        return weightUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.weight_unit_code
     *
     * @param weightUnitCode the value for sinobec_ins_doc_bin.weight_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setWeightUnitCode(String weightUnitCode) {
        this.weightUnitCode = weightUnitCode == null ? null : weightUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.weight_qty
     *
     * @return the value of sinobec_ins_doc_bin.weight_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public BigDecimal getWeightQty() {
        return weightQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.weight_qty
     *
     * @param weightQty the value for sinobec_ins_doc_bin.weight_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setWeightQty(BigDecimal weightQty) {
        this.weightQty = weightQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.bin_weight_unit_code
     *
     * @return the value of sinobec_ins_doc_bin.bin_weight_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getBinWeightUnitCode() {
        return binWeightUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.bin_weight_unit_code
     *
     * @param binWeightUnitCode the value for sinobec_ins_doc_bin.bin_weight_unit_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setBinWeightUnitCode(String binWeightUnitCode) {
        this.binWeightUnitCode = binWeightUnitCode == null ? null : binWeightUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.bin_weight_qty
     *
     * @return the value of sinobec_ins_doc_bin.bin_weight_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public BigDecimal getBinWeightQty() {
        return binWeightQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.bin_weight_qty
     *
     * @param binWeightQty the value for sinobec_ins_doc_bin.bin_weight_qty
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setBinWeightQty(BigDecimal binWeightQty) {
        this.binWeightQty = binWeightQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.stock_status
     *
     * @return the value of sinobec_ins_doc_bin.stock_status
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getStockStatus() {
        return stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.stock_status
     *
     * @param stockStatus the value for sinobec_ins_doc_bin.stock_status
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setStockStatus(String stockStatus) {
        this.stockStatus = stockStatus == null ? null : stockStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.debit_credit
     *
     * @return the value of sinobec_ins_doc_bin.debit_credit
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getDebitCredit() {
        return debitCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.debit_credit
     *
     * @param debitCredit the value for sinobec_ins_doc_bin.debit_credit
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setDebitCredit(String debitCredit) {
        this.debitCredit = debitCredit == null ? null : debitCredit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.refer_receipt_code
     *
     * @return the value of sinobec_ins_doc_bin.refer_receipt_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getReferReceiptCode() {
        return referReceiptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.refer_receipt_code
     *
     * @param referReceiptCode the value for sinobec_ins_doc_bin.refer_receipt_code
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setReferReceiptCode(String referReceiptCode) {
        this.referReceiptCode = referReceiptCode == null ? null : referReceiptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.refer_receipt_rid
     *
     * @return the value of sinobec_ins_doc_bin.refer_receipt_rid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getReferReceiptRid() {
        return referReceiptRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.refer_receipt_rid
     *
     * @param referReceiptRid the value for sinobec_ins_doc_bin.refer_receipt_rid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setReferReceiptRid(String referReceiptRid) {
        this.referReceiptRid = referReceiptRid == null ? null : referReceiptRid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.refer_receipt_bid
     *
     * @return the value of sinobec_ins_doc_bin.refer_receipt_bid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public String getReferReceiptBid() {
        return referReceiptBid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.refer_receipt_bid
     *
     * @param referReceiptBid the value for sinobec_ins_doc_bin.refer_receipt_bid
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setReferReceiptBid(String referReceiptBid) {
        this.referReceiptBid = referReceiptBid == null ? null : referReceiptBid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.refer_receipt_type
     *
     * @return the value of sinobec_ins_doc_bin.refer_receipt_type
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public Integer getReferReceiptType() {
        return referReceiptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.refer_receipt_type
     *
     * @param referReceiptType the value for sinobec_ins_doc_bin.refer_receipt_type
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setReferReceiptType(Integer referReceiptType) {
        this.referReceiptType = referReceiptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.is_delete
     *
     * @return the value of sinobec_ins_doc_bin.is_delete
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.is_delete
     *
     * @param isDelete the value for sinobec_ins_doc_bin.is_delete
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.write_off
     *
     * @return the value of sinobec_ins_doc_bin.write_off
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public Byte getWriteOff() {
        return writeOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.write_off
     *
     * @param writeOff the value for sinobec_ins_doc_bin.write_off
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setWriteOff(Byte writeOff) {
        this.writeOff = writeOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.create_time
     *
     * @return the value of sinobec_ins_doc_bin.create_time
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.create_time
     *
     * @param createTime the value for sinobec_ins_doc_bin.create_time
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.modify_time
     *
     * @return the value of sinobec_ins_doc_bin.modify_time
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.modify_time
     *
     * @param modifyTime the value for sinobec_ins_doc_bin.modify_time
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.create_user_id
     *
     * @return the value of sinobec_ins_doc_bin.create_user_id
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.create_user_id
     *
     * @param createUserId the value for sinobec_ins_doc_bin.create_user_id
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sinobec_ins_doc_bin.modify_user_id
     *
     * @return the value of sinobec_ins_doc_bin.modify_user_id
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sinobec_ins_doc_bin.modify_user_id
     *
     * @param modifyUserId the value for sinobec_ins_doc_bin.modify_user_id
     *
     * @mbg.generated Mon Mar 23 19:57:25 CST 2020
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

	public Integer getStockId() {
		return stockId;
	}

	public void setStockId(Integer stockId) {
		this.stockId = stockId;
	}
    
	private String vendorCode;

	private String vendorName;

	public String getVendorCode() {
		return vendorCode;
	}

	public void setVendorCode(String vendorCode) {
		this.vendorCode = vendorCode;
	}

	public String getVendorName() {
		return vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

    public String getMatName() {
        return matName;
    }

    public void setMatName(String matName) {
        this.matName = matName;
    }

    public String getReferReceiptTypeName() {
        return referReceiptTypeName;
    }

    public void setReferReceiptTypeName(String referReceiptTypeName) {
        this.referReceiptTypeName = referReceiptTypeName;
    }

    private String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}